"""Add recommendation table

Revision ID: 30504cbf80e5
Revises: 
Create Date: 2025-10-04 19:51:44.437353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30504cbf80e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('estimated_saving_min', sa.Integer(), nullable=True),
    sa.Column('estimated_saving_max', sa.Integer(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=True),
    sa.Column('benefit_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('overlap', 'unused', 'switch', 'bundle', 'tip', name='recommendationkind'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefits.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###

